### ISSUE TITLE
How to force webchat version when embedding ?

### ISSUE THREAD

**Issue by Gullfaxi171** [MicrosoftDocs/bot-docs.fr-fr#5]
Hi,

the provided embed link :
`<iframe src="https://webchat.botframework.com/embed/YOUR_BOT_ID?s=YOUR_SECRET_HERE"></iframe>`
forces the webchat version at 4.6.0, which misses some features. Is it possible to select within the url the used version of the webchat (for instantce 4.9.0 or 4.9.1 ?)

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 2d54408c-bfbc-9d2c-a642-ec54f375475f
* Version Independent ID: 5b06e016-1aa8-a13b-179c-ec6700b8287c
* Content: [Connecter un bot au canal Discussion Web - Bot Service - Bot Service](https://docs.microsoft.com/fr-fr/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-webchat.md](https://github.com/MicrosoftDocs/bot-docs.fr-fr/blob/live/articles/bot-service-channel-connect-webchat.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by srvbpigh** [comment]
Hello, @Gullfaxi171
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @Gullfaxi171, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/bot-docs/issues/1729. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
